theme: PaperMod

baseURL: https://yiwei.dev
title: 禅心剑气相思骨
paginate: 7

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 禅心剑气相思骨
  description: Yiwei Gong's Blog
  keywords: [Blog, Portfolio]
  author: Yiwei Gong

  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: 禅心剑气相思骨
    Content: 欢迎访问我的博客，这里包含我的一些技术分享，思考，生活感悟。

  socialIcons:
    - name: GitHub
      url: https://github.com/imwithye
    - name: LinkedIn
      url: https://www.linkedin.com/in/yiwei-gong/
    - name: Rss
      url: "index.xml"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 50